# Generated by Django 3.1.7 on 2021-03-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0002_auto_20210321_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bubble',
            name='bubbs',
        ),
        migrations.AddField(
            model_name='bubble',
            name='subBubbles',
            field=models.ForeignKey(blank=True, db_column='derivedBubbles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subBubbs', to='D3App.bubble'),
        ),
    ]
