# Generated by Django 3.1.7 on 2021-03-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0003_auto_20210321_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bubble',
            name='subBubbles',
        ),
        migrations.AddField(
            model_name='bubble',
            name='bubbs',
            field=models.ManyToManyField(blank=True, db_column='relatedBubbles', null=True, related_name='bubbles', to='D3App.Bubble'),
        ),
        migrations.AddField(
            model_name='bubble',
            name='subBubbs',
            field=models.ForeignKey(blank=True, db_column='derivedBubbles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subBubbles', to='D3App.bubble'),
        ),
    ]
