# Generated by Django 3.1.7 on 2021-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0006_auto_20210323_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bubble',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ev',
        ),
        migrations.AddField(
            model_name='event',
            name='bubbles',
            field=models.ManyToManyField(blank=True, db_column='relatedBubbles', null=True, related_name='relatedBubbles', to='D3App.Bubble'),
        ),
        migrations.AddField(
            model_name='event',
            name='events',
            field=models.ManyToManyField(blank=True, db_column='relatedEvents', null=True, related_name='relatedEvents', to='D3App.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
