# Generated by Django 3.1.7 on 2021-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0009_auto_20210326_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
