# Generated by Django 3.1.7 on 2021-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0010_auto_20210326_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bubbles',
            field=models.ManyToManyField(blank=True, db_column='relatedBubbles', null=True, related_name='relatedEvents', to='D3App.Bubble'),
        ),
    ]
