# Generated by Django 3.1.3 on 2021-04-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0012_auto_20210419_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
