# Generated by Django 3.1.7 on 2021-03-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubble',
            name='bubbs',
            field=models.ManyToManyField(blank=True, db_column='relatedBubbles', null=True, related_name='bubbles', to='D3App.Bubble'),
        ),
    ]
