# Generated by Django 3.1.7 on 2021-03-21 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0004_auto_20210321_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bubble',
            name='subBubbs',
        ),
        migrations.AddField(
            model_name='bubble',
            name='motherBubble',
            field=models.ForeignKey(blank=True, db_column='motherBubble', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subBubbles', to='D3App.bubble'),
        ),
    ]
