# Generated by Django 3.1.7 on 2021-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0007_auto_20210326_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.CharField(default='Content of the event', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Name of the event', max_length=200),
        ),
    ]
