# Generated by Django 3.1.3 on 2021-04-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3App', '0011_auto_20210326_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubble',
            name='bubbs',
            field=models.ManyToManyField(blank=True, db_column='relatedBubbles', related_name='bubbles', to='D3App.Bubble'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bubbles',
            field=models.ManyToManyField(blank=True, db_column='relatedBubbles', related_name='relatedEvents', to='D3App.Bubble'),
        ),
        migrations.AlterField(
            model_name='event',
            name='events',
            field=models.ManyToManyField(blank=True, db_column='relatedEvents', related_name='relatedEvents', to='D3App.Event'),
        ),
    ]
